name: Run Python script
run-name: ci-manual-run-python-script

on:
  workflow_dispatch:
    inputs:
      data:
        description: Data
        required: true
      info:
        type: boolean
        description: Include table of new/removed trips

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      DATA: ${{ github.event.inputs.data }}
      INFO_FLAG: ${{ github.event.inputs.info && '--info' || '' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd code
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python script
      run: python app.py $DATA $INFO_FLAG
